// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"zgo/api"
	"zgo/repo"
	"zgo/service"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) api.UserAPI {
	userRepo := repo.CreateUserRepo(db)
	userService := service.CreateUserService(userRepo)
	userAPI := api.CreateUserAPI(userService)
	return userAPI
}
